# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202112

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 0.11 -3.52 -2.47 -0.76 -2.28]
 [ 2.07  0.91  2.76  0.81  2.21]
 [ 0.86  1.41  0.02 -0.65 -0.68]]
 
[[-0.57  3.32  0.37  2.31]
 [ 0.47 -5.44 -1.7   0.27]
 [-0.39 -2.   -1.    0.74]
 [-1.1   4.09  0.59  1.5 ]
 [-0.13  0.79  0.05  0.74]
 [-0.06 -0.25  0.19 -1.3 ]
 [ 0.09 -1.05  0.48 -3.52]]


# Using pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-3.9600,  0.8600, -4.6500,  2.7200,  0.0300,  2.0500, -5.7200],
        [-5.7900,  1.9100, -5.0000,  4.1800,  0.0700, -1.6500, -0.3500],
        [-1.4800, -0.2400, -1.9100,  0.3600, -0.3700,  0.8700, -2.2500]],
       dtype=torch.float64)
 
tensor([[-3.9600,  0.8600, -4.6500,  2.7200,  0.0300,  2.0500, -5.7200],
        [-5.7900,  1.9100, -5.0000,  4.1800,  0.0700, -1.6500, -0.3500],
        [-1.4800, -0.2400, -1.9100,  0.3600, -0.3700,  0.8700, -2.2500]])
